# https://github.com/JohnnyMorganz/StyLua/tree/main
syntax = "Lua54" # All
column_width = 120
line_endings = "Windows" # Unix
indent_type = "Tabs"
indent_width = 4
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never"
space_after_function_names = "Never"
block_newline_gaps = "Never"

[sort_requires]
enabled = false